default_platform(:ios)

platform :ios do

  def api_key
    app_store_connect_api_key(
      key_id: "3PF72JBJ45",
      issuer_id: "0d7cd2d5-68c7-4214-854f-26b663d40beb",
      key_filepath: "./fastlane/AuthKey_3PF72JBJ45.p8"
    )
  end

  desc "Build for App Store"
  lane :build do
    build_app(
      scheme: "WrenchLog",
      configuration: "Release",
      export_method: "app-store",
      clean: true,
      output_directory: "./build",
      output_name: "WrenchLog.ipa"
    )
  end

  desc "Upload build to ASC"
  lane :upload do
    build
    upload_to_app_store(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      precheck_include_in_app_purchases: false,
      force: true
    )
  end

  desc "Full: build + upload + submit"
  lane :release do
    build
    upload_to_app_store(
      api_key: api_key,
      skip_metadata: true,
      skip_screenshots: true,
      submit_for_review: true,
      automatic_release: true,
      force: true,
      precheck_include_in_app_purchases: false,
      run_precheck_before_submit: false,
      submission_information: {
        add_id_info_uses_idfa: false
      }
    )
  end

end
